bind 0.0.0.0
protected-mode no
requirepass <TEMPLATE-PASSWORD>
port 6379
tcp-backlog 65535
maxclients 100000
timeout 0
tcp-keepalive 0
daemonize no
supervised no
loglevel debug
databases 16
appendonly yes
save ""
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 1024
zset-max-ziplist-entries 256
zset-max-ziplist-value 128
hll-sparse-max-bytes 6000
activerehashing yes
maxmemory-policy allkeys-lru
